---
--- Generated by Luanalysis
--- Created by Jake.
--- DateTime: 08/06/2022 09:59
---

print("This is being executed on the ScriptInit event!")

function AttackBlockEvent(event)
    print(event:setReturnVal(FAIL))
end

function Exit()
    print("Exiting")
end



